import { canonTeam } from "./teamMatch";

// Canonical team name (lowercase, accent-stripped, aliased via canonTeam) → flagcdn.com code.
// Codes are ISO 3166-1 alpha-2, plus flagcdn's non-ISO FIFA entries (gb-eng etc., xk).
// Covers the plausible 2026 World Cup field; extend as unmapped names surface.
const TEAM_FLAG_CODES: Record<string, string> = {
  // UEFA
  albania: "al",
  austria: "at",
  belgium: "be",
  bosnia: "ba",
  croatia: "hr",
  "czech republic": "cz",
  czechia: "cz",
  denmark: "dk",
  england: "gb-eng",
  finland: "fi",
  france: "fr",
  georgia: "ge",
  germany: "de",
  greece: "gr",
  hungary: "hu",
  iceland: "is",
  ireland: "ie",
  "republic of ireland": "ie",
  italy: "it",
  kosovo: "xk",
  netherlands: "nl",
  "north macedonia": "mk",
  "northern ireland": "gb-nir",
  norway: "no",
  poland: "pl",
  portugal: "pt",
  romania: "ro",
  scotland: "gb-sct",
  serbia: "rs",
  slovakia: "sk",
  slovenia: "si",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  turkey: "tr",
  ukraine: "ua",
  wales: "gb-wls",
  // CONMEBOL
  argentina: "ar",
  bolivia: "bo",
  brazil: "br",
  chile: "cl",
  colombia: "co",
  ecuador: "ec",
  paraguay: "py",
  peru: "pe",
  uruguay: "uy",
  venezuela: "ve",
  // CONCACAF
  canada: "ca",
  "costa rica": "cr",
  curacao: "cw",
  "el salvador": "sv",
  guatemala: "gt",
  haiti: "ht",
  honduras: "hn",
  jamaica: "jm",
  mexico: "mx",
  panama: "pa",
  suriname: "sr",
  "trinidad and tobago": "tt",
  usa: "us",
  // AFC
  australia: "au",
  bahrain: "bh",
  china: "cn",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  japan: "jp",
  jordan: "jo",
  kuwait: "kw",
  "north korea": "kp",
  "korea dpr": "kp",
  oman: "om",
  qatar: "qa",
  "saudi arabia": "sa",
  "south korea": "kr",
  "united arab emirates": "ae",
  uzbekistan: "uz",
  // CAF
  algeria: "dz",
  angola: "ao",
  benin: "bj",
  "burkina faso": "bf",
  cameroon: "cm",
  "cape verde": "cv",
  "dr congo": "cd",
  egypt: "eg",
  gabon: "ga",
  ghana: "gh",
  guinea: "gn",
  "ivory coast": "ci",
  mali: "ml",
  morocco: "ma",
  nigeria: "ng",
  senegal: "sn",
  "south africa": "za",
  tunisia: "tn",
  zambia: "zm",
  // OFC
  "new caledonia": "nc",
  "new zealand": "nz",
};

// null when the team isn't mapped — callers fall back to the initials avatar.
export function teamFlagCode(name: string): string | null {
  return TEAM_FLAG_CODES[canonTeam(name)] ?? null;
}
